//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterMembership.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BetterMembership.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with Users as (
        ///	Select	ROW_NUMBER() Over (Order By m.UserId) As Row,
        ///			p.[userId] UserId
        ///	From [UserProfile] p
        ///		inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///	Where p.[email] like &apos;%&apos;+@2+&apos;%&apos;
        ///)
        ///Select	(Select COUNT(*) From Users) Total,
        ///		p.[userId] UserId, 
        ///		[userName] UserName,
        ///		m.[IsConfirmed] IsConfirmed,
        ///		m.[lastPasswordFailureDate] LastPasswordFailureDate,
        ///		m.[PasswordFailuresSinceLastSuccess] PasswordFailuresSinceLastSuccess,
        ///		m.[createDate] creationDate,
        ///		m.[passwo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlFindUsersByEmail {
            get {
                return ResourceManager.GetString("SqlFindUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with Users as (
        ///	Select	ROW_NUMBER() Over (Order By m.UserId) As Row,
        ///			p.[userId] UserId
        ///	From [UserProfile] p
        ///		inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///	Where p.[userName] like &apos;%&apos;+@2+&apos;%&apos;
        ///)
        ///Select	(Select COUNT(*) From Users) Total,
        ///		p.[userId] UserId, 
        ///		[userName] UserName,
        ///		m.[IsConfirmed] IsConfirmed,
        ///		m.[lastPasswordFailureDate] LastPasswordFailureDate,
        ///		m.[PasswordFailuresSinceLastSuccess] PasswordFailuresSinceLastSuccess,
        ///		m.[createDate] creationDate,
        ///		m.[pas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlFindUsersByName {
            get {
                return ResourceManager.GetString("SqlFindUsersByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;with Users as (
        ///	Select	ROW_NUMBER() Over (Order By m.UserId) As Row,
        ///			p.[userId] UserId
        ///	From [UserProfile] p
        ///		inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///)
        ///Select	(Select COUNT(*) From Users) Total,
        ///		p.[userId] UserId, 
        ///		[userName] UserName,
        ///		m.[IsConfirmed] IsConfirmed,
        ///		m.[lastPasswordFailureDate] LastPasswordFailureDate,
        ///		m.[PasswordFailuresSinceLastSuccess] PasswordFailuresSinceLastSuccess,
        ///		m.[createDate] creationDate,
        ///		m.[passwordChangedDate] PasswordChangedDate [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SqlGetAllUsers {
            get {
                return ResourceManager.GetString("SqlGetAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	0 Total, 
        ///		p.[userId] UserId, 
        ///		p.[userName] UserName,
        ///		m.[IsConfirmed] IsConfirmed,
        ///		m.[lastPasswordFailureDate] LastPasswordFailureDate,
        ///		m.[PasswordFailuresSinceLastSuccess] PasswordFailuresSinceLastSuccess,
        ///		m.[createDate] creationDate,
        ///		m.[passwordChangedDate] PasswordChangedDate,
        ///		p.[email] Email
        ///From [UserProfile] p
        ///	  inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///Where UPPER(p.[userName]) = UPPER(@0).
        /// </summary>
        internal static string SqlGetUser {
            get {
                return ResourceManager.GetString("SqlGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	0 Total,
        ///		p.[userId] UserId, 
        ///		[userName] UserName,
        ///		m.[IsConfirmed] IsConfirmed,
        ///		m.[lastPasswordFailureDate] LastPasswordFailureDate,
        ///		m.[PasswordFailuresSinceLastSuccess] PasswordFailuresSinceLastSuccess,
        ///		m.[createDate] creationDate,
        ///		m.[passwordChangedDate] PasswordChangedDate,
        ///		p.[email] Email
        ///From	[UserProfile] p
        ///		inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///Where	p.[userId] = @0.
        /// </summary>
        internal static string sqlGetUserById {
            get {
                return ResourceManager.GetString("sqlGetUserById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select	p.[userName] UserName
        ///From	[UserProfile] p
        ///		inner join [webpages_Membership] m on m.UserId=p.[userId]
        ///Where	p.[email] = @0.
        /// </summary>
        internal static string sqlGetUserNameByEmail {
            get {
                return ResourceManager.GetString("sqlGetUserNameByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update  m
        ///Set		PasswordFailuresSinceLastSuccess = 0,
        ///		LastPasswordFailureDate = null
        ///From	UserProfile p
        ///		inner join webpages_Membership m on m.UserId = p.[userId]
        ///Where	p.[userName] = @0.
        /// </summary>
        internal static string sqlUnlockUser {
            get {
                return ResourceManager.GetString("sqlUnlockUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update p
        ///Set	 p.[email] = @1
        ///From [UserProfile] p
        ///Where p.[email] != @1 AND UPPER(p.[userName]) = UPPER(@0);
        ///Update m
        ///Set	 m.IsConfirmed = @2
        ///From [UserProfile] p
        ///	  inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///Where m.IsConfirmed != @2 And UPPER(p.[userName]) = UPPER(@0);.
        /// </summary>
        internal static string sqlUpdateUserWithEmail {
            get {
                return ResourceManager.GetString("sqlUpdateUserWithEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update m
        ///Set	 m.IsConfirmed = @1
        ///From [UserProfile] p
        ///	  inner join [webpages_Membership] m on m.UserId=p.[UserId]
        ///Where m.IsConfirmed != @1 And UPPER(p.[userName]) = UPPER(@0).
        /// </summary>
        internal static string sqlUpdateUserWithoutEmail {
            get {
                return ResourceManager.GetString("sqlUpdateUserWithoutEmail", resourceCulture);
            }
        }
    }
}
